const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto');
const express=require('express');const {WebSocketServer}=require('ws');
let pgPool=null,saveQueue=Promise.resolve();
const app=express(),server=http.createServer(app),wss=new WebSocketServer({server,maxPayload:64*1024});
app.set('trust proxy', 1);
app.disable('x-powered-by');
const PORT=Number(process.env.PORT||8080),DB_FILE=process.env.DB_FILE||path.join(__dirname,'..','data','db.json'),APP_NAMESPACE=String(process.env.APP_NAMESPACE||'ureyimsen-web-v26');
const allowed=(process.env.CORS_ORIGINS||'https://ureyimsen.com,https://www.ureyimsen.com,http://localhost:8080,http://localhost:3000').split(',').map(s=>s.trim());
app.use((req,res,next)=>{const o=req.headers.origin;if(!o||allowed.includes(o))res.setHeader('Access-Control-Allow-Origin',o||'*');res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,DELETE,OPTIONS');if(req.method==='OPTIONS')return res.sendStatus(204);next()});
app.use(express.json({limit:'4mb'}));
app.get('/api/railway-status',(q,r)=>r.json({ok:true,platform:'railway',port:PORT,websocket:true,production:process.env.NODE_ENV==='production',database:process.env.DATABASE_URL?'postgres':'file'}));app.use(express.static(path.join(__dirname,'..','public')));
function emptyDb(){return {users:{},sessions:{},rooms:{},wallets:{},messages:[],transactions:[],gifts:[],pk:{},moments:[],follows:{},notifications:{},ludo:{},calls:{},redEnvelopes:{},idempotency:{}}}
function load(){try{return JSON.parse(fs.readFileSync(DB_FILE,'utf8'))}catch{return emptyDb()}}
let db=load();for(const k of ['users','rooms','wallets','messages','transactions','gifts','pk','moments','follows','notifications','ludo','calls','redEnvelopes','idempotency'])if(!db[k])db[k]=k==='messages'||k==='transactions'||k==='moments'?[]:{};
function save(){const snapshot=JSON.stringify(db);if(!pgPool){fs.mkdirSync(path.dirname(DB_FILE),{recursive:true});fs.writeFileSync(DB_FILE,snapshot);return Promise.resolve()}saveQueue=saveQueue.then(()=>pgPool.query('INSERT INTO app_state(key,data,updated_at) VALUES($1,$2::jsonb,NOW()) ON CONFLICT(key) DO UPDATE SET data=EXCLUDED.data,updated_at=NOW()',[APP_NAMESPACE,snapshot])).catch(e=>console.error('database save failed',e.message));return saveQueue}
function sessionUserId(token){const sess=db.sessions[token];const id=typeof sess==='string'?sess:sess?.userId;const exp=typeof sess==='object'?Number(sess.expiresAt||0):0;if(!id||(exp&&exp<Date.now()))return null;return id}
function auth(req,res,next){const h=String(req.headers.authorization||'');const token=h.startsWith('Bearer ')?h.slice(7):'';const sess=db.sessions[token];const id=typeof sess==='string'?sess:sess?.userId;const exp=typeof sess==='object'?Number(sess.expiresAt||0):0;if(!token||!id||!db.users[id]||(exp&&exp<Date.now())){if(token&&exp&&exp<Date.now()){delete db.sessions[token];save()}return res.status(401).json({error:'unauthorized'})}req.user=db.users[id];req.sessionToken=token;next()}
function safeUser(u){const x={...u};delete x.passwordHash;return x}
function sameUser(req,id){return req.user&&req.user.id===String(id)}
function roomMember(roomId,userId){const x=db.rooms[roomId];return !!(x&&x.viewers&&x.viewers[userId])}
function roomHost(roomId,userId){const x=db.rooms[roomId];return !!(x&&x.host===userId)}
function roomModerator(roomId,userId){const x=db.rooms[roomId];return !!(x&&(x.host===userId||(x.admins||[]).includes(userId)))}
function requireRoomModerator(req,res,next){const id=req.params.id||req.body?.roomId;if(!db.rooms[id]||db.rooms[id].closed)return res.status(404).json({error:'room_not_found'});if(!roomModerator(id,req.user.id))return res.status(403).json({error:'moderator_required'});next()}
function requireRoomHost(req,res,next){const id=req.params.id||req.body?.roomId;if(!db.rooms[id]||db.rooms[id].closed)return res.status(404).json({error:'room_not_found'});if(!roomHost(id,req.user.id))return res.status(403).json({error:'host_required'});next()}
function clampInt(v,min,max,d=min){const n=Number(v);return Number.isInteger(n)?Math.max(min,Math.min(max,n)):d}
function cleanText(v,n=500){return String(v??'').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').slice(0,n)}
function requestKey(req){const k=String(req.headers['idempotency-key']||'').trim();return k&&k.length<=128?k:''}
function cachedResponse(req,userId){const k=requestKey(req);return k?db.idempotency[userId+':'+k]:null}
function cacheResponse(req,userId,payload){const k=requestKey(req);if(!k)return;db.idempotency[userId+':'+k]={at:Date.now(),payload};const keys=Object.keys(db.idempotency);if(keys.length>5000){for(const key of keys.sort((a,b)=>db.idempotency[a].at-db.idempotency[b].at).slice(0,keys.length-5000))delete db.idempotency[key]}}
const gifts=[['rose','🌹','Rose',10],['heart','❤️','Heart',20],['diamond','💎','Diamond',100],['cake','🎂','Cake',250],['car','🚗','Car',500],['crown','👑','Crown',1000],['rocket','🚀','Rocket',5000],['love','💖','Love Rain',10000]];
const giftAssets={rose:'moment_like.pag',heart:'heart.pag',diamond:'vip_dynamic_avatar_sample.pag',cake:'game_point_get_money_anim.pag',car:'live_pk_start_bmp.pag',crown:'main_tab_vip.pag',rocket:'pk_win.pag',love:'super_red_packet.pag'};
function uid(){return crypto.randomUUID()}
function hashPassword(password){const salt=crypto.randomBytes(16);const hash=crypto.scryptSync(String(password),salt,64);return salt.toString('hex')+':'+hash.toString('hex')}
function verifyPassword(password,stored){try{const [s,h]=String(stored).split(':');if(!s||!h)return false;const salt=Buffer.from(s,'hex'),expected=Buffer.from(h,'hex'),actual=crypto.scryptSync(String(password),salt,expected.length);return crypto.timingSafeEqual(actual,expected)}catch{return false}}
function user(id,name){if(!db.users[id]){db.users[id]={id,name:name||'Guest',createdAt:Date.now(),vip:0,level:1,followers:0,following:0,bio:'',avatar:'',email:'',passwordHash:'',rating:0,likes:0,giftsReceived:0,giftsSent:0};db.wallets[id]={coins:0};db.notifications[id]=[];save()}return db.users[id]}
function normalizeRoom(x){if(!x)return x;x.viewers=x.viewers||{};x.seats=Array.isArray(x.seats)?x.seats.slice(0,12):[];while(x.seats.length<12)x.seats.push(null);x.admins=Array.isArray(x.admins)?x.admins:[];x.banned=Array.isArray(x.banned)?x.banned:[];x.seatRequests=x.seatRequests||{};x.seatLocks=Array.isArray(x.seatLocks)?x.seatLocks.slice(0,12):[];while(x.seatLocks.length<12)x.seatLocks.push(false);x.micMuted=x.micMuted||{};x.kickHistory=Array.isArray(x.kickHistory)?x.kickHistory:[];x.announcement=cleanText(x.announcement||'',500);x.cover=cleanText(x.cover||'',1000);x.tags=Array.isArray(x.tags)?x.tags.slice(0,5).map(v=>cleanText(v,30)):[];return x}
function normalizeAllRooms(){for(const x of Object.values(db.rooms||{}))normalizeRoom(x)}
normalizeAllRooms();
function room(id){if(!db.rooms[id])db.rooms[id]={id,title:'Xena Room',type:'video',host:null,viewers:{},seats:Array(12).fill(null),admins:[],banned:[],locked:false,seatMode:'open',seatRequests:{},seatLocks:Array(12).fill(false),micMuted:{},kickHistory:[],announcement:'',cover:'',tags:[],createdAt:Date.now(),music:null};return normalizeRoom(db.rooms[id])}
function broadcast(r,msg){for(const c of wss.clients)if(c.readyState===1&&c.roomId===r)c.send(JSON.stringify(msg))}
function notify(id,n){if(!db.notifications[id])db.notifications[id]=[];const item={id:uid(),at:Date.now(),read:false,...n};db.notifications[id].unshift(item);db.notifications[id]=db.notifications[id].slice(0,200);for(const c of wss?.clients||[])if(c.readyState===1&&c.userId===id)c.send(JSON.stringify({type:'notification',notification:item}))}
app.get('/health',(q,r)=>r.json({ok:true,service:'xena-web',time:new Date().toISOString()}));
setInterval(()=>{let changed=false;const now=Date.now();for(const [token,s] of Object.entries(db.sessions)){const exp=typeof s==='object'?Number(s.expiresAt||0):0;if(exp&&exp<now){delete db.sessions[token];changed=true}}for(const [key,v] of Object.entries(db.idempotency||{})){if(!v||now-Number(v.at||0)>24*60*60*1000){delete db.idempotency[key];changed=true}}if(changed)save()},10*60*1000);
setInterval(()=>{const cutoff=Date.now()-1000*60*60*24;let changed=false;for(const x of Object.values(db.rooms)){if(x.closed||x.viewers&&Object.keys(x.viewers).length)continue;if(x.createdAt<cutoff){x.closed=true;x.closedAt=Date.now();changed=true}}if(changed)save()},10*60*1000);
app.get('/api/config',(q,r)=>r.json({version:'v26',origin:'ureyimsen.com',apiBase:'/api',allowedOrigins:allowed,developmentRecharge:process.env.ALLOW_DEV_RECHARGE==='true',features:{video:true,audio:true,gifts:true,pk:true,pkInvites:true,ludo:true,moments:true,vip:true,wallet:true,notifications:true,privateLink:true,roomAnnouncement:true,seatControl:true,redEnvelope:true},media:{mode:process.env.LIVEKIT_URL?'livekit':'mesh',livekitUrl:process.env.LIVEKIT_URL||null},webrtc:{iceServers:[{urls:'stun:stun.l.google.com:19302'}].concat(process.env.TURN_URL?[{urls:process.env.TURN_URL,username:process.env.TURN_USERNAME||'',credential:process.env.TURN_CREDENTIAL||''}]:[])}}));
function b64u(v){return Buffer.from(v).toString('base64').replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
function livekitJwt(apiKey,secret,identity,roomName){const now=Math.floor(Date.now()/1000),header=b64u(JSON.stringify({alg:'HS256',typ:'JWT'})),payload=b64u(JSON.stringify({iss:apiKey,sub:identity,nbf:now-5,exp:now+3600,video:{roomJoin:true,room:roomName,canPublish:true,canSubscribe:true,canPublishData:true}})),data=header+'.'+payload,sig=crypto.createHmac('sha256',secret).update(data).digest('base64').replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');return data+'.'+sig}
app.post('/api/livekit/token',auth,(q,r)=>{const url=String(process.env.LIVEKIT_URL||'').trim(),key=String(process.env.LIVEKIT_API_KEY||''),secret=String(process.env.LIVEKIT_API_SECRET||''),roomName=String(q.body?.roomId||'').trim();if(!url||!key||!secret)return r.status(503).json({error:'livekit_not_configured'});if(!roomName||!db.rooms[roomName])return r.status(404).json({error:'room_not_found'});const x=db.rooms[roomName];if(x.banned.includes(q.user.id)||x.locked&&x.host!==q.user.id)return r.status(403).json({error:x.banned.includes(q.user.id)?'banned':'room_locked'});r.json({url,token:livekitJwt(key,secret,q.user.id,roomName),roomId:roomName,identity:q.user.id})});
app.post('/api/rooms/:id/seat-mode',auth,requireRoomHost,(q,r)=>{const x=db.rooms[q.params.id],mode=String(q.body?.mode||'open');if(!x||x.closed)return r.status(404).json({error:'room_not_found'});if(!['open','request','host_only'].includes(mode))return r.status(400).json({error:'invalid_seat_mode'});x.seatMode=mode;save();broadcast(x.id,{type:'room',room:x});r.json(x)});
app.post('/api/rooms/:id/seat-request',auth,(q,r)=>{const x=db.rooms[q.params.id],uid0=q.user.id;if(!x||x.closed)return r.status(404).json({error:'room_not_found'});;if(!roomMember(x.id,uid0)||x.host===uid0)return r.status(403).json({error:'room_required'});if(x.banned.includes(uid0))return r.status(403).json({error:'banned'});if((x.seatMode||'open')!=='request')return r.status(409).json({error:'seat_requests_disabled'});x.seatRequests=x.seatRequests||{};const existing=x.seatRequests[uid0];if(existing?.status==='pending')return r.json(existing);const req={id:uid(),userId:uid0,name:q.user.name,seat:clampInt(q.body?.seat,0,11,0),status:'pending',createdAt:Date.now()};x.seatRequests[uid0]=req;notify(x.host,{type:'seat_request',roomId:x.id,request:req});save();broadcast(x.id,{type:'seat_request',request:req});r.json(req)});
app.post('/api/rooms/:id/seat-request/:userId',auth,requireRoomHost,(q,r)=>{const x=normalizeRoom(db.rooms[q.params.id]);if(!x||x.closed)return r.status(404).json({error:'room_not_found'});const target=String(q.params.userId),req=x.seatRequests?.[target],action=String(q.body?.action||'');if(!req)return r.status(404).json({error:'request_not_found'});if(!['accept','decline'].includes(action))return r.status(400).json({error:'invalid_action'});if(action==='accept'){const i=clampInt(req.seat,0,11,-1);if(i<0)return r.status(400).json({error:'invalid_seat'});if(x.seatLocks[i])return r.status(409).json({error:'seat_locked'});if(x.seats[i]&&x.seats[i].userId!==target)return r.status(409).json({error:'seat_taken'});x.seats=x.seats.map((v,n)=>n===i?{userId:target,name:db.users[target]?.name||req.name}:(v?.userId===target?null:v));}req.status=action==='accept'?'accepted':'declined';req.resolvedAt=Date.now();notify(target,{type:'seat_request_result',roomId:x.id,request:req});save();broadcast(x.id,{type:'seat_request_result',request:req,room:x});r.json(req)});
app.get('/api/gifts',(q,r)=>r.json(gifts.map(([id,icon,name,price])=>({id,icon,name,price,asset:giftAssets[id]}))));
app.get('/api/gifts/banner',(q,r)=>r.json({title:'Hədiyyələr',items:gifts.map(([id,icon,name,price])=>({id,icon,name,price,asset:giftAssets[id]}))}));
app.get('/api/gifts/tips',(q,r)=>r.json({tips:['Hədiyyə göndərmək üçün balansında coin olmalıdır.','Combo hədiyyələr ardıcıl göndərişləri birləşdirir.','VIP səviyyəsi hədiyyə və profil üstünlükləri verir.']}));
app.get('/api/gifts/history',auth,(q,r)=>{const roomId=String(q.query.roomId||'');const rows=db.gifts.filter(x=>(!roomId||x.roomId===roomId)&&(x.userId===q.user.id||x.toUserId===q.user.id)).slice(-200).reverse();r.json(rows)});
const httpRate=new Map();
function httpLimited(req,key,max,windowMs){const ip=String(req.ip||req.headers['x-forwarded-for']||'unknown').split(',')[0].trim();const k=ip+':'+key;const now=Date.now();let a=httpRate.get(k)||[];a=a.filter(t=>now-t<windowMs);if(a.length>=max){httpRate.set(k,a);return false}a.push(now);httpRate.set(k,a);return true}
app.post('/api/auth/guest',(q,r)=>{if(!httpLimited(q,'guest',10,60000))return r.status(429).json({error:'rate_limited'});const id=uid(),token=crypto.randomBytes(32).toString('hex'),u=user(id,String(q.body?.name||'Guest').slice(0,32));db.sessions[token]={userId:id,expiresAt:Date.now()+1000*60*60*24*30};save();r.json({token,user:safeUser(u),wallet:db.wallets[id]})});
app.post('/api/auth/register',(q,r)=>{if(!httpLimited(q,'register',8,60000))return r.status(429).json({error:'rate_limited'});const email=String(q.body?.email||'').trim().toLowerCase();const password=String(q.body?.password||'');const name=cleanText(q.body?.name||'User',32);if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)||password.length<6)return r.status(400).json({error:'invalid_credentials'});if(Object.values(db.users).some(u=>u.email===email))return r.status(409).json({error:'email_exists'});const id=uid(),u=user(id,name);u.email=email;u.passwordHash=hashPassword(password);const token=crypto.randomBytes(32).toString('hex');db.sessions[token]={userId:id,expiresAt:Date.now()+1000*60*60*24*30};save();r.json({token,user:safeUser(u),wallet:db.wallets[id]})});
app.post('/api/auth/login',(q,r)=>{if(!httpLimited(q,'login',12,60000))return r.status(429).json({error:'rate_limited'});const email=String(q.body?.email||'').trim().toLowerCase(),password=String(q.body?.password||'');const u=Object.values(db.users).find(x=>x.email===email);if(!u||!verifyPassword(password,u.passwordHash))return r.status(401).json({error:'invalid_credentials'});const token=crypto.randomBytes(32).toString('hex');db.sessions[token]={userId:u.id,expiresAt:Date.now()+1000*60*60*24*30};save();r.json({token,user:safeUser(u),wallet:db.wallets[u.id]})});
app.post('/api/auth/logout',auth,(q,r)=>{delete db.sessions[q.sessionToken];save();r.json({ok:true})});
app.get('/api/rooms',(q,r)=>r.json(Object.values(db.rooms).filter(x=>!x.closed).map(x=>({...x,viewerCount:Object.keys(x.viewers).length,seatCount:x.seats.filter(Boolean).length}))));
app.post('/api/rooms/:id/close',auth,requireRoomHost,(q,r)=>{const x=db.rooms[q.params.id];x.closed=true;x.closedAt=Date.now();save();broadcast(x.id,{type:'room_closed',roomId:x.id});r.json({ok:true,room:x})});
app.post('/api/rooms/:id/host-transfer',auth,requireRoomHost,(q,r)=>{const x=db.rooms[q.params.id],to=String(q.body?.userId||'');if(!x.viewers[to])return r.status(400).json({error:'target_not_in_room'});const old=x.host;x.host=to;for(const v of Object.values(x.viewers))v.host=v.userId===to;save();broadcast(x.id,{type:'room',room:x});r.json({ok:true,oldHost:old,host:to,room:x})});

app.post('/api/rooms',auth,(q,r)=>{const id=uid(),x=room(id);x.title=cleanText(q.body?.title||'Xena Room',80);x.type=['video','audio'].includes(q.body?.type)?q.body.type:'video';x.host=q.user.id;x.viewers[q.user.id]={userId:q.user.id,name:q.user.name,joinedAt:Date.now(),host:true};save();r.json(x)});
app.get('/api/rooms/:id',(q,r)=>{const x=db.rooms[q.params.id];if(!x||x.closed)return r.status(404).json({error:'room_not_found'});r.json(x)});
app.post('/api/rooms/:id/join',auth,(q,r)=>{const x=normalizeRoom(db.rooms[q.params.id]);if(!x||x.closed)return r.status(404).json({error:'room_not_found'});if(x.banned.includes(q.user.id))return r.status(403).json({error:'banned'});if(x.locked&&x.host!==q.user.id)return r.status(403).json({error:'room_locked'});if(!x.viewers[q.user.id]&&Object.keys(x.viewers).length>=1000)return r.status(409).json({error:'room_full'});const existed=!!x.viewers[q.user.id];if(!existed)x.viewers[q.user.id]={userId:q.user.id,name:q.user.name,joinedAt:Date.now(),host:x.host===q.user.id};save();if(!existed)broadcast(x.id,{type:'presence',action:'join',user:x.viewers[q.user.id],room:x});r.json(x)});
app.get('/api/rooms/:id/viewers',(q,r)=>{const x=db.rooms[q.params.id];if(!x)return r.status(404).json({error:'room_not_found'});r.json(Object.values(x.viewers||{}).map(v=>({...v,user:db.users[v.userId]?safeUser(db.users[v.userId]):null,seat:(x.seats||[]).findIndex(s=>s?.userId===v.userId)})))});
app.get('/api/rooms/:id/config',(q,r)=>{const x=normalizeRoom(db.rooms[q.params.id]);if(!x)return r.status(404).json({error:'room_not_found'});r.json({roomId:x.id,type:x.type,title:x.title,announcement:x.announcement,cover:x.cover,tags:x.tags,seatCount:x.seats.length,maxViewers:1000,locked:x.locked,music:x.music,seatMode:x.seatMode||'open',seatLocks:x.seatLocks,micMuted:x.micMuted,admins:x.admins||[],features:{chat:true,gifts:true,pk:true,seats:true,redEnvelope:true,video:x.type==='video',audio:true}})});
app.get('/api/rooms/:id/messages',auth,(q,r)=>{const x=db.rooms[q.params.id];if(!x)return r.status(404).json({error:'room_not_found'});if(!roomMember(x.id,q.user.id)&&!roomHost(x.id,q.user.id))return r.status(403).json({error:'room_required'});const limit=clampInt(q.query?.limit,1,200,100);r.json(db.messages.filter(m=>m.roomId===x.id).slice(-limit).map(m=>({...m,name:db.users[m.userId]?.name||'Guest',vip:db.users[m.userId]?.vip||0})))})
app.put('/api/rooms/:id',auth,requireRoomHost,(q,r)=>{
 const x=normalizeRoom(db.rooms[q.params.id]);
 if(!x||x.closed)return r.status(404).json({error:'room_not_found'});
 if(q.body?.title!==undefined)x.title=cleanText(q.body.title,80)||x.title;
 if(q.body?.type!==undefined&&['video','audio'].includes(q.body.type))x.type=q.body.type;
 if(q.body?.locked!==undefined)x.locked=!!q.body.locked;
 if(q.body?.announcement!==undefined)x.announcement=cleanText(q.body.announcement,500);
 if(q.body?.cover!==undefined)x.cover=cleanText(q.body.cover,1000);
 if(q.body?.tags!==undefined)x.tags=Array.isArray(q.body.tags)?q.body.tags.slice(0,5).map(v=>cleanText(v,30)).filter(Boolean):[];
 if(q.body?.music!==undefined){
  if(q.body.music===null)x.music=null;
  else{
   const u=cleanText(q.body.music?.url,1000);
   try{const parsed=new URL(u);if(!['http:','https:'].includes(parsed.protocol))throw Error('protocol')}catch{return r.status(400).json({error:'invalid_music_url'})}
   x.music={title:cleanText(q.body.music?.title,120),url:u};
  }
 }
 save();broadcast(x.id,{type:'room',room:x});r.json(x);
});
app.post('/api/rooms/:id/admins',auth,requireRoomHost,(q,r)=>{const x=db.rooms[q.params.id];if(!x||x.closed)return r.status(404).json({error:'room_not_found'});const target=String(q.body?.userId||'');if(!db.users[target])return r.status(404).json({error:'user_not_found'});if(target===x.host)return r.status(400).json({error:'host_is_not_admin'});if(!x.admins.includes(target))x.admins.push(target);save();notify(target,{type:'room_admin',roomId:x.id,role:'admin'});broadcast(x.id,{type:'room',room:x});r.json({admins:x.admins})})
app.delete('/api/rooms/:id/admins/:userId',auth,requireRoomHost,(q,r)=>{const x=db.rooms[q.params.id];if(!x||x.closed)return r.status(404).json({error:'room_not_found'});x.admins=x.admins.filter(id=>id!==String(q.params.userId));save();broadcast(x.id,{type:'room',room:x});r.json({admins:x.admins})})
app.post('/api/rooms/:id/moderation',auth,requireRoomModerator,(q,r)=>{const x=normalizeRoom(db.rooms[q.params.id]);if(!x||x.closed)return r.status(404).json({error:'room_not_found'});const target=String(q.body?.userId||''),action=String(q.body?.action||'');if(!target||!['kick','ban','unban'].includes(action))return r.status(400).json({error:'invalid_moderation'});if(target===x.host)return r.status(400).json({error:'cannot_moderate_host'});if(action==='ban'){if(!x.banned.includes(target))x.banned.push(target);delete x.viewers[target];x.seats=x.seats.map(v=>v?.userId===target?null:v);notify(target,{type:'room_ban',roomId:x.id})}else if(action==='unban'){x.banned=x.banned.filter(id=>id!==target)}else{delete x.viewers[target];x.seats=x.seats.map(v=>v?.userId===target?null:v);notify(target,{type:'room_kick',roomId:x.id})}x.kickHistory.unshift({id:uid(),userId:target,action,by:q.user.id,at:Date.now()});x.kickHistory=x.kickHistory.slice(0,200);save();for(const c of wss.clients)if(c.readyState===1&&c.roomId===x.id&&c.userId===target&&['kick','ban'].includes(action))c.close(4003,action);broadcast(x.id,{type:'room',room:x});r.json({ok:true,action,userId:target})})
app.delete('/api/rooms/:id/messages/:messageId',auth,requireRoomModerator,(q,r)=>{const x=db.rooms[q.params.id];if(!x||x.closed)return r.status(404).json({error:'room_not_found'});const m=db.messages.find(v=>v.id===q.params.messageId&&v.roomId===x.id);if(!m)return r.status(404).json({error:'message_not_found'});m.deleted=true;m.text='[Mesaj silindi]';m.deletedAt=Date.now();m.deletedBy=q.user.id;save();broadcast(x.id,{type:'message_deleted',messageId:m.id});r.json({ok:true,messageId:m.id})})
app.delete('/api/rooms/:id/messages',auth,requireRoomModerator,(q,r)=>{const x=db.rooms[q.params.id];if(!x||x.closed)return r.status(404).json({error:'room_not_found'});for(const m of db.messages.filter(v=>v.roomId===x.id)){m.deleted=true;m.text='[Mesaj silindi]';m.deletedAt=Date.now();m.deletedBy=q.user.id}save();broadcast(x.id,{type:'chat_cleared'});r.json({ok:true})})
app.post('/api/rooms/:id/seat',auth,(q,r)=>{const uid0=q.user.id;const x=normalizeRoom(db.rooms[q.params.id]);if(!uid0||!x)return r.status(!x?404:401).json({error:!x?'room_not_found':'unauthorized'});if(!roomMember(x.id,uid0)&&!roomHost(x.id,uid0))return r.status(403).json({error:'room_required'});if(x.banned.includes(uid0)||x.locked&&x.host!==uid0)return r.status(403).json({error:x.banned.includes(uid0)?'banned':'room_locked'});const i=clampInt(q.body?.seat,0,x.seats.length-1,-1),take=q.body?.take!==false;if(i<0)return r.status(400).json({error:'invalid_seat'});if(take){if(x.seatLocks[i]&&!roomModerator(x.id,uid0))return r.status(409).json({error:'seat_locked'});if((x.seatMode||'open')==='host_only'&&!roomModerator(x.id,uid0))return r.status(403).json({error:'host_only'});if((x.seatMode||'open')==='request'&&!roomModerator(x.id,uid0))return r.status(409).json({error:'seat_request_required'});if(x.seats[i]&&x.seats[i].userId!==uid0)return r.status(409).json({error:'seat_taken'});x.seats=x.seats.map((v,n)=>n===i?{userId:uid0,name:db.users[uid0]?.name||'Guest'}:(v?.userId===uid0?null:v))}else if(x.seats[i]?.userId===uid0||roomModerator(x.id,uid0))x.seats[i]=null;save();broadcast(x.id,{type:'room',room:x});r.json(x)});
app.get('/api/users/search',(q,r)=>{const term=String(q.query.q||'').trim().toLowerCase();if(!term)return r.json([]);r.json(Object.values(db.users).filter(u=>u.name.toLowerCase().includes(term)||u.id.toLowerCase()===term).slice(0,30).map(u=>({id:u.id,name:u.name,vip:u.vip,level:u.level,avatar:u.avatar}))) });
app.post('/api/rooms/:id/leave',auth,(q,r)=>{const x=db.rooms[q.params.id];if(!x)return r.status(404).json({error:'room_not_found'});const uid0=q.user.id;if(uid0===x.host)return r.status(400).json({error:'host_must_close_or_transfer'});const existed=!!x.viewers[uid0];delete x.viewers[uid0];x.seats=x.seats.map(v=>v?.userId===uid0?null:v);if(x.seatRequests?.[uid0])delete x.seatRequests[uid0];save();if(existed)broadcast(x.id,{type:'presence',action:'leave',userId:uid0,room:x});r.json({ok:true,room:x})});
app.post('/api/rooms/:id/settings',auth,requireRoomHost,(q,r)=>{const x=normalizeRoom(db.rooms[q.params.id]);if(!x||x.closed)return r.status(404).json({error:'room_not_found'});if(q.body?.title!==undefined)x.title=cleanText(q.body.title,80)||x.title;if(q.body?.locked!==undefined)x.locked=!!q.body.locked;if(q.body?.announcement!==undefined)x.announcement=cleanText(q.body.announcement,500);save();broadcast(x.id,{type:'room',room:x});r.json(x)});
app.get('/api/rooms/:id/admin',auth,requireRoomModerator,(q,r)=>{const x=normalizeRoom(db.rooms[q.params.id]);if(!x||x.closed)return r.status(404).json({error:'room_not_found'});r.json({admins:x.admins,banned:x.banned,viewers:Object.values(x.viewers),seatRequests:Object.values(x.seatRequests).filter(v=>v.status==='pending'),seatLocks:x.seatLocks,micMuted:x.micMuted,kickHistory:x.kickHistory})});
app.post('/api/rooms/:id/seat-lock',auth,requireRoomModerator,(q,r)=>{const x=normalizeRoom(db.rooms[q.params.id]);if(!x||x.closed)return r.status(404).json({error:'room_not_found'});const seat=clampInt(q.body?.seat,0,11,-1);if(seat<0)return r.status(400).json({error:'invalid_seat'});x.seatLocks[seat]=q.body?.locked!==false;save();broadcast(x.id,{type:'room',room:x});r.json({seat,locked:x.seatLocks[seat],room:x})});
app.post('/api/rooms/:id/mic',auth,(q,r)=>{const x=normalizeRoom(db.rooms[q.params.id]);if(!x||x.closed)return r.status(404).json({error:'room_not_found'});const target=String(q.body?.userId||q.user.id);if(target!==q.user.id&&!roomModerator(x.id,q.user.id))return r.status(403).json({error:'moderator_required'});if(!x.viewers[target])return r.status(404).json({error:'user_not_in_room'});x.micMuted[target]=q.body?.muted!==false;save();broadcast(x.id,{type:'mic',userId:target,muted:x.micMuted[target],room:x});r.json({userId:target,muted:x.micMuted[target]})});
app.get('/api/rooms/:id/kick-history',auth,requireRoomModerator,(q,r)=>{const x=normalizeRoom(db.rooms[q.params.id]);if(!x)return r.status(404).json({error:'room_not_found'});r.json(x.kickHistory)});
app.get('/api/rooms/:id/red-envelopes',auth,(q,r)=>{const x=db.rooms[q.params.id];if(!x)return r.status(404).json({error:'room_not_found'});if(!roomMember(x.id,q.user.id)&&!roomHost(x.id,q.user.id))return r.status(403).json({error:'room_required'});r.json(Object.values(db.redEnvelopes).filter(v=>v.roomId===x.id&&v.expiresAt>Date.now()))});
app.post('/api/rooms/:id/red-envelopes',auth,(q,r)=>{const x=db.rooms[q.params.id],userId=q.user.id;if(!x)return r.status(404).json({error:'room_not_found'});if(!roomMember(x.id,userId)&&!roomHost(x.id,userId))return r.status(403).json({error:'room_required'});const coins=clampInt(q.body?.coins,1,1000000,0),shares=clampInt(q.body?.shares,1,100,0);if(!coins||!shares||shares>coins)return r.status(400).json({error:'invalid_red_envelope'});if((db.wallets[userId]?.coins||0)<coins)return r.status(400).json({error:'insufficient_coins'});db.wallets[userId].coins-=coins;const item={id:uid(),roomId:x.id,userId,coins,remainingCoins:coins,shares,remainingShares:shares,claims:[],createdAt:Date.now(),expiresAt:Date.now()+600000};db.redEnvelopes[item.id]=item;db.transactions.push({id:uid(),type:'red_envelope_create',userId,roomId:x.id,coins,at:Date.now()});save();broadcast(x.id,{type:'red_envelope',action:'created',envelope:{...item,claims:[]}});r.json({envelope:item,wallet:db.wallets[userId]})});
app.post('/api/rooms/:id/red-envelopes/:envelopeId/claim',auth,(q,r)=>{const x=db.rooms[q.params.id],item=db.redEnvelopes[q.params.envelopeId],userId=q.user.id;if(!x||!item||item.roomId!==q.params.id)return r.status(404).json({error:'red_envelope_not_found'});if(!roomMember(x.id,userId)&&!roomHost(x.id,userId))return r.status(403).json({error:'room_required'});if(item.expiresAt<=Date.now()||item.remainingShares<=0)return r.status(409).json({error:'red_envelope_closed'});const prior=item.claims.find(c=>c.userId===userId);if(prior)return r.status(409).json({error:'already_claimed',claim:prior});const amount=item.remainingShares===1?item.remainingCoins:Math.max(1,Math.floor(item.remainingCoins/item.remainingShares));const claim={userId,name:q.user.name,coins:amount,at:Date.now()};item.claims.push(claim);item.remainingCoins-=amount;item.remainingShares--;db.wallets[userId].coins+=amount;db.transactions.push({id:uid(),type:'red_envelope_claim',userId,roomId:x.id,envelopeId:item.id,coins:amount,at:Date.now()});save();broadcast(x.id,{type:'red_envelope',action:'claimed',envelopeId:item.id,claim});r.json({claim,envelope:item,wallet:db.wallets[userId]})});
app.get('/api/ranking/rating',(q,r)=>{const rows=Object.values(db.users).map(u=>({userId:u.id,name:u.name,rating:u.rating||0,level:u.level||1,vip:u.vip||0,giftsSent:u.giftsSent||0,giftsReceived:u.giftsReceived||0})).sort((a,b)=>b.rating-a.rating).slice(0,100).map((x,i)=>({...x,rank:i+1}));r.json(rows)});
app.get('/api/ranking',(q,r)=>{const rows=Object.entries(db.wallets).map(([id,w])=>({userId:id,coins:w.coins,rating:db.users[id]?.rating||0,name:db.users[id]?.name||'Guest',vip:db.users[id]?.vip||0})).sort((a,b)=>b.coins-a.coins).slice(0,100).map((x,i)=>({...x,rank:i+1}));r.json(rows)});
app.get('/api/profile/:id',(q,r)=>{const u=db.users[q.params.id];if(!u)return r.status(404).json({error:'user_not_found'});const followers=Object.values(db.follows).filter(x=>x.to===u.id&&x.active).length;const following=Object.values(db.follows).filter(x=>x.from===u.id&&x.active).length;r.json({...safeUser(u),followers,following,wallet:db.wallets[u.id]})});
app.put('/api/profile/:id',auth,(q,r)=>{if(!sameUser(q,q.params.id))return r.status(403).json({error:'forbidden'});const u=user(q.params.id);for(const k of ['name','bio','avatar'])if(q.body?.[k]!==undefined)u[k]=String(q.body[k]).slice(0,500);save();r.json({...safeUser(u),wallet:db.wallets[u.id]})});
app.post('/api/follow',auth,(q,r)=>{const {from,to}=q.body||{};if(!sameUser(q,from))return r.status(403).json({error:'forbidden'});if(!from||!to||from===to)return r.status(400).json({error:'invalid_follow'});if(!db.users[from]||!db.users[to])return r.status(404).json({error:'user_not_found'});user(from);user(to);const key=from+'_'+to;db.follows[key]={from,to,active:!db.follows[key]?.active};if(db.follows[key].active){db.users[to].followers++;db.users[from].following++;notify(to,{type:'follow',from,name:db.users[from].name})}else{db.users[to].followers=Math.max(0,db.users[to].followers-1);db.users[from].following=Math.max(0,db.users[from].following-1)}save();r.json(db.follows[key])});
app.get('/api/moments',(q,r)=>r.json(db.moments.slice(-200).reverse().map(m=>({...m,author:db.users[m.userId]?.name||'Guest'}))));
app.post('/api/moments',auth,(q,r)=>{const {userId,text,media=''}=q.body||{};if(!sameUser(q,userId))return r.status(403).json({error:'forbidden'});user(userId);const m={id:uid(),userId,text:String(text||'').slice(0,1000),media:String(media||'').slice(0,200000),likes:[],at:Date.now()};db.moments.push(m);save();r.json(m)});
app.post('/api/moments/:id/like',auth,(q,r)=>{const m=db.moments.find(x=>x.id===q.params.id);if(!m)return r.status(404).end();const id=q.user.id;if(!m.likes.includes(id))m.likes.push(id);else m.likes=m.likes.filter(x=>x!==id);save();r.json({likes:m.likes.length,liked:m.likes.includes(id)})});
app.get('/api/notifications/:id',auth,(q,r)=>{if(!sameUser(q,q.params.id))return r.status(403).json({error:'forbidden'});r.json(db.notifications[q.params.id]||[])});
app.get('/api/notifications/:id/unread-count',auth,(q,r)=>{if(!sameUser(q,q.params.id))return r.status(403).json({error:'forbidden'});const n=(db.notifications[q.params.id]||[]).filter(x=>!x.read).length;r.json({count:n})});
app.post('/api/notifications/:id/read',auth,(q,r)=>{if(!sameUser(q,q.params.id))return r.status(403).json({error:'forbidden'});for(const n of db.notifications[q.params.id]||[])n.read=true;save();r.json({ok:true})});
app.get('/api/wallet/:id',auth,(q,r)=>{if(!sameUser(q,q.params.id))return r.status(403).json({error:'forbidden'});r.json(db.wallets[q.params.id]||null)});
app.post('/api/wallet/recharge',auth,(q,r)=>{if(process.env.ALLOW_DEV_RECHARGE!=='true')return r.status(403).json({error:'recharge_disabled'});const userId=q.body?.userId||q.user.id;if(userId!==q.user.id)return r.status(403).json({error:'forbidden'});const {coins}=q.body||{};user(userId);const n=clampInt(coins,1,1000000,0);if(!n)return r.status(400).json({error:'invalid_coins'});db.wallets[userId].coins+=n;db.transactions.push({id:uid(),type:'recharge',userId,coins:n,at:Date.now()});save();r.json(db.wallets[userId])});
app.get('/api/wallet/transactions',auth,(q,r)=>{const limit=clampInt(q.query?.limit,1,200,50);r.json(db.transactions.filter(x=>x.userId===q.user.id).slice(-limit).reverse())});
app.get('/api/wallet/:id/transactions',auth,(q,r)=>{if(!sameUser(q,q.params.id))return r.status(403).json({error:'forbidden'});r.json(db.transactions.filter(x=>x.userId===q.params.id).slice(-200).reverse())});
app.post('/api/gifts/send',auth,(q,r)=>{const {roomId,giftId,toSeat,quantity=1}=q.body||{},userId=q.user.id,g=gifts.find(x=>x[0]===giftId);const cached=cachedResponse(q,userId);if(cached)return r.json(cached.payload);if(!roomId||!db.rooms[roomId])return r.status(404).json({error:'room_not_found'});if(!roomMember(roomId,userId)&&!roomHost(roomId,userId))return r.status(403).json({error:'room_required'});if(!g)return r.status(404).json({error:'gift_not_found'});user(userId);const qty=Math.max(1,Math.min(999,Number(quantity)||1)),cost=g[3]*qty;if((db.wallets[userId]?.coins||0)<cost)return r.status(400).json({error:'insufficient_coins'});db.wallets[userId].coins-=cost;db.transactions.push({id:uid(),type:'gift',userId,roomId,giftId,quantity:qty,cost,at:Date.now()});const requestedSeat=Number(toSeat);const target=Number.isInteger(requestedSeat)&&requestedSeat>=0&&requestedSeat<db.rooms[roomId].seats.length?db.rooms[roomId].seats[requestedSeat]:Object.values(db.rooms[roomId].viewers||{}).find(v=>v.userId===db.rooms[roomId].host)||null;db.gifts.push({id:uid(),userId,roomId,giftId,quantity:qty,cost,toUserId:target?.userId||null,at:Date.now()});db.gifts=db.gifts.slice(-20000);db.users[userId].giftsSent=(db.users[userId].giftsSent||0)+qty;db.users[userId].rating=(db.users[userId].rating||0)+qty;if(target?.userId&&db.users[target.userId]){db.users[target.userId].giftsReceived=(db.users[target.userId].giftsReceived||0)+qty;db.users[target.userId].rating=(db.users[target.userId].rating||0)+qty*2;notify(target.userId,{type:'gift',from:userId,roomId,giftId,quantity:qty})}save();broadcast(roomId,{type:'gift',userId,giftId,toSeat,quantity:qty,cost,asset:giftAssets[giftId]});const payload={ok:true,wallet:db.wallets[userId],gift:{id:g[0],name:g[2],icon:g[1],price:g[3],asset:giftAssets[giftId]}};cacheResponse(q,userId,payload);save();r.json(payload)});
app.post('/api/gifts/combo',auth,(q,r)=>{const {roomId,giftId,toSeat,count=1}=q.body||{},userId=q.user.id;const cached=cachedResponse(q,userId);if(cached)return r.json(cached.payload);if(!roomId||!db.rooms[roomId])return r.status(404).json({error:'room_not_found'});if(!roomMember(roomId,userId)&&!roomHost(roomId,userId))return r.status(403).json({error:'room_required'});const g=gifts.find(x=>x[0]===giftId);if(!g)return r.status(404).json({error:'gift_not_found'});user(userId);const n=Math.max(1,Math.min(99,Number(count)||1)),cost=g[3]*n;if(db.wallets[userId].coins<cost)return r.status(400).json({error:'insufficient_coins'});db.wallets[userId].coins-=cost;db.users[userId].giftsSent=(db.users[userId].giftsSent||0)+n;db.users[userId].rating=(db.users[userId].rating||0)+n;const requestedSeat=Number(toSeat);const comboTarget=Number.isInteger(requestedSeat)&&requestedSeat>=0&&requestedSeat<db.rooms[roomId].seats.length?db.rooms[roomId].seats[requestedSeat]:Object.values(db.rooms[roomId].viewers||{}).find(v=>v.userId===db.rooms[roomId].host)||null;if(comboTarget?.userId&&db.users[comboTarget.userId]){db.users[comboTarget.userId].giftsReceived=(db.users[comboTarget.userId].giftsReceived||0)+n;db.users[comboTarget.userId].rating=(db.users[comboTarget.userId].rating||0)+n*2;notify(comboTarget.userId,{type:'gift',from:userId,roomId,giftId,quantity:n,combo:true})}db.transactions.push({id:uid(),type:'gift_combo',userId,roomId,giftId,quantity:n,cost,at:Date.now()});const event={id:uid(),userId,roomId,giftId,toSeat,quantity:n,cost,asset:giftAssets[giftId],combo:true};db.gifts.push({id:event.id,userId,roomId,giftId,quantity:n,cost,toUserId:comboTarget?.userId||null,combo:true,at:Date.now()});db.gifts=db.gifts.slice(-20000);broadcast(roomId,{type:'gift',...event});const payload={ok:true,wallet:db.wallets[userId],event};cacheResponse(q,userId,payload);save();r.json(payload)});
app.post('/api/vip/buy',auth,(q,r)=>{const {level=1}=q.body||{},userId=q.user.id;user(userId);const l=Math.max(1,Math.min(10,Number(level)||1)),cost=l*5000;if(db.wallets[userId].coins<cost)return r.status(400).json({error:'insufficient_coins'});db.wallets[userId].coins-=cost;db.users[userId].vip=Math.max(db.users[userId].vip,l);db.transactions.push({id:uid(),type:'vip',userId,level:l,cost,at:Date.now()});save();return r.json({user:db.users[userId],wallet:db.wallets[userId]})});
app.get('/api/vip/config',(q,r)=>r.json({levels:Array.from({length:10},(_,i)=>({level:i+1,price:(i+1)*5000,benefits:['VIP badge','special chat style','gift effects','priority room entry'].slice(0,Math.min(4,Math.ceil((i+1)/3))) }))}));
app.post('/api/pk/start',auth,(q,r)=>{const {roomId,to}=q.body||{};if(!roomHost(roomId,q.user.id))return r.status(403).json({error:'host_required'});const x=db.rooms[roomId],from=q.user.id,target=String(to||'');if(!x)return r.status(404).json({error:'room_not_found'});if(!target||target===from||!x.viewers[target])return r.status(400).json({error:'invalid_opponent'});const current=db.pk[roomId];if(current&&['invited','active'].includes(current.status))return r.status(409).json({error:'pk_busy'});db.pk[roomId]={id:uid(),status:'invited',from,to:target,a:0,b:0,invitedAt:Date.now(),expiresAt:Date.now()+60000,duration:300};notify(target,{type:'pk_invite',roomId,from,pkId:db.pk[roomId].id});save();broadcast(roomId,{type:'pk',pk:db.pk[roomId]});r.json(db.pk[roomId])});
app.post('/api/pk/:roomId/respond',auth,(q,r)=>{const pk=db.pk[q.params.roomId],action=String(q.body?.action||'');if(!pk||pk.status!=='invited')return r.status(404).json({error:'pk_invite_not_found'});if(pk.to!==q.user.id)return r.status(403).json({error:'pk_target_required'});if(pk.expiresAt<Date.now()){pk.status='expired';save();return r.status(409).json({error:'pk_invite_expired'})}if(!['accept','decline'].includes(action))return r.status(400).json({error:'invalid_action'});pk.status=action==='accept'?'active':'declined';pk.respondedAt=Date.now();if(pk.status==='active')pk.startedAt=Date.now();save();broadcast(q.params.roomId,{type:'pk',pk});r.json(pk)});
app.post('/api/pk/:roomId/cancel',auth,(q,r)=>{const pk=db.pk[q.params.roomId];if(!pk||pk.status!=='invited')return r.status(404).json({error:'pk_invite_not_found'});if(pk.from!==q.user.id)return r.status(403).json({error:'pk_inviter_required'});pk.status='cancelled';pk.cancelledAt=Date.now();save();broadcast(q.params.roomId,{type:'pk',pk});r.json(pk)});
app.post('/api/pk/score',auth,(q,r)=>{const {roomId,side,points}=q.body||{},pk=db.pk[roomId];if(!pk||pk.status!=='active')return r.status(404).json({error:'no_pk'});if(Date.now()-pk.startedAt>pk.duration*1000){pk.status='ended';pk.endedAt=Date.now();save();broadcast(roomId,{type:'pk',pk});return r.status(409).json({error:'pk_expired',pk})}const wanted=side==='b'?'b':'a',actor=q.user.id;if((wanted==='a'&&actor!==pk.from)||(wanted==='b'&&actor!==pk.to))return r.status(403).json({error:'pk_side_forbidden'});const n=Math.max(0,Math.min(100000,Number(points)||0));pk[wanted]+=n;save();broadcast(roomId,{type:'pk',pk});r.json(pk)});
app.post('/api/pk/end',auth,(q,r)=>{if(!roomHost(q.body?.roomId,q.user.id))return r.status(403).json({error:'host_required'});if(!db.pk[q.body?.roomId])return r.status(404).end();db.pk[q.body.roomId].status='ended';db.pk[q.body.roomId].endedAt=Date.now();save();broadcast(q.body.roomId,{type:'pk',pk:db.pk[q.body.roomId]});r.json(db.pk[q.body.roomId])});
app.get('/api/pk/:roomId',(q,r)=>r.json(db.pk[q.params.roomId]||null));
app.post('/api/private-link/request',auth,(q,r)=>{const {to,roomId}=q.body||{};const from=q.user.id;if(!to||from===to||!db.users[to])return r.status(400).json({error:'invalid_call'});if(roomId){const x=db.rooms[roomId];if(!x)return r.status(404).json({error:'room_not_found'});if(x.banned.includes(from)||x.banned.includes(String(to)))return r.status(403).json({error:'banned'});if(!roomMember(roomId,from)||!roomMember(roomId,String(to)))return r.status(403).json({error:'room_required'})}const id=uid();db.calls[id]={id,from,to,roomId,status:'ringing',createdAt:Date.now()};notify(to,{type:'private_call',callId:id,from,roomId});save();r.json(db.calls[id])});
app.post('/api/private-link/:id',auth,(q,r)=>{const c=db.calls[q.params.id];if(!c||![c.from,c.to].includes(q.user.id))return r.status(c?403:404).json({error:c?'forbidden':'not_found'});if(!c)return r.status(404).end();c.status=['accept','decline','end'].includes(q.body?.action)?q.body.action:c.status;save();if(c.roomId)broadcast(c.roomId,{type:'private_link',call:c});r.json(c)});
app.get('/api/ludo/:roomId',(q,r)=>r.json(db.ludo[q.params.roomId]||null));
function newLudo(id,mode='classic'){return {roomId:id,mode:mode==='2v2'?'2v2':'classic',status:'waiting',players:[],turn:0,lastRoll:null,lastUser:null,winner:null,createdAt:Date.now(),board:{}}}
app.post('/api/ludo/:roomId/start',auth,(q,r)=>{const id=q.params.roomId;if(!roomMember(id,q.user.id)&&!roomHost(id,q.user.id))return r.status(403).json({error:'room_required'});const current=db.ludo[id];if(current&&(current.status==='active'||current.status==='waiting')&&current.owner!==q.user.id)return r.status(403).json({error:'ludo_owner_required'});db.ludo[id]=newLudo(id,q.body?.mode);db.ludo[id].owner=q.user.id;save();broadcast(id,{type:'ludo',game:db.ludo[id]});r.json(db.ludo[id])});
app.post('/api/ludo/:roomId/join',auth,(q,r)=>{const id=q.params.roomId;if(!roomMember(id,q.user.id)&&!roomHost(id,q.user.id))return r.status(403).json({error:'room_required'});const existing=db.ludo[id];if(existing?.status==='ended')return r.status(409).json({error:'game_ended'});const g=existing||newLudo(id);const uid0=q.user.id;if(!uid0)return r.status(400).json({error:'user_required'});const u=user(uid0);if(!g.players.some(x=>x.userId===u.id)&&g.players.length<4){const idx=g.players.length;g.players.push({userId:u.id,name:u.name,color:['red','blue','green','yellow'][idx],team:g.mode==='2v2'?(idx%2===0?'A':'B'):null,position:-1,finished:0,score:0})}if(g.players.length>=(g.mode==='2v2'?4:2))g.status='active';db.ludo[id]=g;save();broadcast(id,{type:'ludo',game:g});r.json(g)});
app.post('/api/ludo/:roomId/roll',auth,(q,r)=>{const g=db.ludo[q.params.roomId],uid0=q.user.id;if(!g||g.status!=='active')return r.status(400).json({error:'game_not_active'});if(g.players[g.turn]?.userId!==uid0)return r.status(403).json({error:'not_your_turn'});const n=1+Math.floor(Math.random()*6),p=g.players[g.turn];g.lastRoll=n;g.lastUser=uid0;g.rollAt=Date.now();if((p.position<0&&n!==6)||(p.position>=0&&p.position+n>56)){g.lastRoll=null;g.lastUser=null;g.lastMove={userId:uid0,from:p.position,to:p.position,steps:n,skipped:true,at:Date.now()};g.turn=(g.turn+1)%g.players.length}save();broadcast(g.roomId,{type:'ludo',game:g,roll:n,skipped:!!g.lastMove?.skipped});r.json(g)});
app.post('/api/ludo/:roomId/move',auth,(q,r)=>{const g=db.ludo[q.params.roomId],uid0=q.user.id;if(!g||g.status!=='active')return r.status(400).json({error:'game_not_active'});if(g.players[g.turn]?.userId!==uid0)return r.status(403).json({error:'not_your_turn'});const p=g.players[g.turn],steps=Number(g.lastRoll);if(g.lastUser!==uid0||!steps)return r.status(400).json({error:'roll_first'});if(p.position<0&&steps!==6)return r.status(400).json({error:'need_six'});if(p.position>=0&&p.position+steps>56)return r.status(400).json({error:'exact_finish_required'});const old=p.position;p.position=p.position<0?0:p.position+steps;let captured=[];const safe=new Set([0,8,13,21,26,34,39,47]);if(p.position>=0&&p.position<56&&!safe.has(p.position)){for(const other of g.players){if(other.userId!==p.userId&&other.position===p.position&&other.position>=0&&other.position<56){other.position=-1;captured.push(other.userId)}}}g.lastMove={userId:uid0,from:old,to:p.position,steps,captured,at:Date.now()};if(p.position===56){p.finished=1;p.score+=1;g.winner=p.userId;g.status='ended'}else if(steps!==6){g.turn=(g.turn+1)%g.players.length}g.lastRoll=null;g.lastUser=null;save();broadcast(g.roomId,{type:'ludo',game:g});r.json(g)});
app.post('/api/ludo/:roomId/leave',auth,(q,r)=>{const g=db.ludo[q.params.roomId];if(!g)return r.status(404).json({error:'game_not_found'});g.players=g.players.filter(v=>v.userId!==q.user.id);if(g.owner===q.user.id)g.owner=g.players[0]?.userId||null;if(g.players.length<2&&g.status==='active')g.status='waiting';if(!g.players.length)delete db.ludo[q.params.roomId];save();broadcast(q.params.roomId,{type:'ludo',game:db.ludo[q.params.roomId]||null});r.json(db.ludo[q.params.roomId]||null)});
app.post('/api/ludo/:roomId/reset',auth,(q,r)=>{const g=db.ludo[q.params.roomId];if(!g)return r.status(404).json({error:'game_not_found'});if(g.owner!==q.user.id)return r.status(403).json({error:'ludo_owner_required'});const fresh=newLudo(q.params.roomId,g.mode);fresh.owner=q.user.id;db.ludo[q.params.roomId]=fresh;save();broadcast(q.params.roomId,{type:'ludo',game:fresh});r.json(fresh)});
wss.on('connection',(ws,req)=>{
 const origin=String(req.headers.origin||'');if(origin&&!allowed.includes(origin)){ws.close(1008,'origin_not_allowed');return}
 ws.isAlive=true;ws.authed=false;ws.rate={chat:[],signal:[],all:[]};ws.on('pong',()=>{ws.isAlive=true});
 const limited=(kind,max,windowMs)=>{const now=Date.now(),a=ws.rate[kind];while(a.length&&now-a[0]>windowMs)a.shift();if(a.length>=max)return false;a.push(now);return true};
 ws.send(JSON.stringify({type:'hello',serverTime:Date.now()}));
 ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}
  if(!limited('all',120,10000))return;
  if(m.type==='join'){
   const token=String(m.token||''); const uid0=sessionUserId(token);
   if(!uid0||!db.users[uid0])return ws.send(JSON.stringify({type:'error',error:'unauthorized'}));
   const x=normalizeRoom(db.rooms[m.roomId]); if(!x||x.closed)return ws.send(JSON.stringify({type:'error',error:'room_not_found'}));
   const u=db.users[uid0];
   if(x.banned.includes(u.id)||x.locked&&x.host!==u.id)return ws.send(JSON.stringify({type:'error',error:x.banned.includes(u.id)?'banned':'room_locked'}));
   if(!x.viewers[u.id]&&Object.keys(x.viewers).length>=1000)return ws.send(JSON.stringify({type:'error',error:'room_full'}));
   ws.authed=true;ws.sessionToken=token;ws.roomId=x.id;ws.userId=u.id;
   const wasConnected=!!x.viewers[u.id]&&Number(x.viewers[u.id].connections||0)>0;
   if(!x.viewers[u.id])x.viewers[u.id]={userId:u.id,name:u.name,joinedAt:Date.now(),host:x.host===u.id,connections:0};
   x.viewers[u.id].connections=(x.viewers[u.id].connections||0)+1;save();
   if(!wasConnected)broadcast(x.id,{type:'presence',action:'join',user:x.viewers[u.id],room:x});
   ws.send(JSON.stringify({type:'room',room:x,user:safeUser(u),wallet:db.wallets[u.id]}));
  }
  else if(m.type==='chat'&&ws.authed&&ws.roomId){if(!limited('chat',8,2000))return;const msg={id:uid(),roomId:ws.roomId,userId:ws.userId,text:cleanText(m.text),at:Date.now(),deleted:false};if(!msg.text)return;db.messages.push(msg);db.messages=db.messages.slice(-10000);save();broadcast(ws.roomId,{type:'chat',message:{...msg,name:db.users[ws.userId]?.name||'Guest',vip:db.users[ws.userId]?.vip||0}})}
  else if(m.type==='seat'&&ws.authed&&ws.roomId){const x=normalizeRoom(db.rooms[ws.roomId]),i=Number(m.seat),mod=roomModerator(ws.roomId,ws.userId);if(!x||!roomMember(x.id,ws.userId)&&x.host!==ws.userId)return;if((x.seatMode||'open')==='host_only'&&!mod)return;if((x.seatMode||'open')==='request'&&!mod)return;if(i>=0&&i<12){if(m.take&&!x.seats[i]&&(!x.seatLocks[i]||mod))x.seats[i]={userId:ws.userId,name:db.users[ws.userId]?.name};else if(!m.take&&(x.seats[i]?.userId===ws.userId||mod))x.seats[i]=null;save();broadcast(x.id,{type:'room',room:x})}}
  else if(m.type==='webrtc'&&ws.authed&&ws.roomId&&m.to){if(!limited('signal',40,1000))return;for(const c of wss.clients)if(c!==ws&&c.readyState===1&&c.roomId===ws.roomId&&c.userId===m.to)c.send(JSON.stringify({...m,from:ws.userId}))}
  else if(m.type==='typing'&&ws.authed&&ws.roomId)broadcast(ws.roomId,{type:'typing',userId:ws.userId,typing:!!m.typing})
  else if(m.type==='ping')ws.send(JSON.stringify({type:'pong',at:Date.now()}));
 });
 ws.on('close',()=>{if(ws.roomId&&db.rooms[ws.roomId]){const x=db.rooms[ws.roomId],v=x.viewers[ws.userId];if(v){v.connections=Math.max(0,(v.connections||1)-1);if(v.connections===0){delete x.viewers[ws.userId];x.seats=x.seats.map(z=>z?.userId===ws.userId?null:z);save();broadcast(ws.roomId,{type:'presence',action:'leave',userId:ws.userId,room:x})}else save()}}})
});

const heartbeat=setInterval(()=>{for(const ws of wss.clients){if(ws.isAlive===false){ws.terminate();continue}ws.isAlive=false;try{ws.ping()}catch{}}},30000);wss.on('close',()=>clearInterval(heartbeat));
process.on('uncaughtException',e=>console.error('uncaughtException',e));
process.on('unhandledRejection',e=>console.error('unhandledRejection',e));
async function shutdown(signal){
 console.log(`Received ${signal}, shutting down...`);
 try{await new Promise(resolve=>server.close(resolve));}catch{}
 try{if(pgPool)await pgPool.end();}catch{}
 process.exit(0);
}
process.once('SIGTERM',()=>shutdown('SIGTERM'));
process.once('SIGINT',()=>shutdown('SIGINT'));

async function bootstrap(){
 if(process.env.DATABASE_URL){
  try{
   const {Pool}=require('pg');
   pgPool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('localhost')?false:{rejectUnauthorized:false},max:5});
   await pgPool.query('CREATE TABLE IF NOT EXISTS app_state (key text PRIMARY KEY,data jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT NOW())');
   const row=(await pgPool.query('SELECT data FROM app_state WHERE key=$1',[APP_NAMESPACE])).rows[0];
   if(row?.data){db=Object.assign(emptyDb(),row.data);normalizeAllRooms();}
   else await save();
   console.log('Database: PostgreSQL');
  }catch(e){pgPool=null;console.error('PostgreSQL unavailable, using file DB:',e.message)}
 }
 server.listen(PORT,'0.0.0.0',()=>console.log(`Xena Web listening on 0.0.0.0:${PORT}`));
}
bootstrap();
